[package]
name = "soncat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.11", features = ["derive"] }
pretty_assertions = "1.4.0"

[dev-dependencies]
assert_cmd = "2.0.15"
predicates = "3.1.2"
rand = "0.8.5"
